name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'           # creates build/libs/*.jar
      - name: build Gradle
        run: ./gradlew build
      - name: Build Docker image
        run: docker build . --file Dockerfile --build-arg JAR_FILE=build/libs/\*.jar --tag ping:$(date +%s)
