name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: bootJar            # creates build/libs/*.jar
        run: docker build . --file Dockerfile --build-arg JAR_FILE=build/libs/\*.jar --tag ping:$(date +%s)
